// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5bqm9Fbnqw-1-NrtqLgVYVyd5jql72I',
    appId: '1:917071431046:web:11b798c1d8c6e294c0d807',
    messagingSenderId: '917071431046',
    projectId: 'chatapp-39d52',
    authDomain: 'chatapp-39d52.firebaseapp.com',
    storageBucket: 'chatapp-39d52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBINRoktzHk9FwHOpofUw0dCqBapk5Jeo',
    appId: '1:917071431046:android:ace4781b358ded3cc0d807',
    messagingSenderId: '917071431046',
    projectId: 'chatapp-39d52',
    storageBucket: 'chatapp-39d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnTT2GebK9aViMx12yj7TIf3p4pSYtVo',
    appId: '1:917071431046:ios:3639946eefc19960c0d807',
    messagingSenderId: '917071431046',
    projectId: 'chatapp-39d52',
    storageBucket: 'chatapp-39d52.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjnTT2GebK9aViMx12yj7TIf3p4pSYtVo',
    appId: '1:917071431046:ios:3639946eefc19960c0d807',
    messagingSenderId: '917071431046',
    projectId: 'chatapp-39d52',
    storageBucket: 'chatapp-39d52.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5bqm9Fbnqw-1-NrtqLgVYVyd5jql72I',
    appId: '1:917071431046:web:77d4580426846617c0d807',
    messagingSenderId: '917071431046',
    projectId: 'chatapp-39d52',
    authDomain: 'chatapp-39d52.firebaseapp.com',
    storageBucket: 'chatapp-39d52.appspot.com',
  );
}
